name: "Default Workspace"
repos: {}
  #  - path: "ui"
  #    git: "git@github.com:MultiRepo-Workspace/ui.git"
  #    branch: "develop"
build: {}
  # - path: "ui"
  #   execute:
  #     - kind: cmd
  #       name: npm
  #       args:
  #         - install
  #     - kind: script
  #       name: build.sh
config:
  port: 8080
  # Use hub sync for sync repo from remote
  pull: hub
  # Use git pull for sync repo from remote
  # pull: git
